// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJcojmJpxTTDhLlW8w-OGaZZgCcu07P8Y',
    appId: '1:61831554804:web:fa0fc8496bfbc44b5420a1',
    messagingSenderId: '61831554804',
    projectId: 'seat-easy-ac-project',
    authDomain: 'seat-easy-ac-project.firebaseapp.com',
    storageBucket: 'seat-easy-ac-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzBbpPD34KT53CUwraDh2qQ9Rusx7RJZ8',
    appId: '1:61831554804:android:b39ea75dcd10b7825420a1',
    messagingSenderId: '61831554804',
    projectId: 'seat-easy-ac-project',
    storageBucket: 'seat-easy-ac-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_vQ5enuky3Z4q_InOoVxA4UqufvTrLeM',
    appId: '1:61831554804:ios:00f3dfa9030652675420a1',
    messagingSenderId: '61831554804',
    projectId: 'seat-easy-ac-project',
    storageBucket: 'seat-easy-ac-project.firebasestorage.app',
    iosBundleId: 'com.example.seatEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_vQ5enuky3Z4q_InOoVxA4UqufvTrLeM',
    appId: '1:61831554804:ios:00f3dfa9030652675420a1',
    messagingSenderId: '61831554804',
    projectId: 'seat-easy-ac-project',
    storageBucket: 'seat-easy-ac-project.firebasestorage.app',
    iosBundleId: 'com.example.seatEasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJcojmJpxTTDhLlW8w-OGaZZgCcu07P8Y',
    appId: '1:61831554804:web:67fcd1d0f980c63e5420a1',
    messagingSenderId: '61831554804',
    projectId: 'seat-easy-ac-project',
    authDomain: 'seat-easy-ac-project.firebaseapp.com',
    storageBucket: 'seat-easy-ac-project.firebasestorage.app',
  );
}
